using ToneCustoms.ShellStudio.Core;using ToneCustoms.ShellStudio.Export;using ToneCustoms.ShellStudio.Geometry;using ToneCustoms.ShellStudio.Validation;using Xunit;
namespace ToneCustoms.ShellStudio.Tests;
public class CoreTests {
[Fact]public void GridSnapWorks(){var v=new GeometryService().Snap(new Vec3(1.12f,.61f,.1f),.25f);Assert.Equal(1f,v.X);Assert.Equal(.5f,v.Y);Assert.Equal(0f,v.Z);}
[Fact]public void WallHasExpectedType()=>Assert.Equal(SceneObjectType.Wall,new GeometryService().Wall(new Vec3()).Type);
[Fact]public void EmptyProjectWarns()=>Assert.Contains(new ProjectValidator().Validate(new ShellProject()),x=>x.Area=="Geometry");
[Fact]public void RoomGeneratorCreatesShell(){var items=new RoomGenerator().Generate(new Vec3(),5,5).ToList();Assert.Equal(6,items.Count);Assert.Equal(4,items.Count(x=>x.Type==SceneObjectType.Wall));}
[Fact]public void WallOpeningPersists(){var p=new ShellProject();var w=new GeometryService().Wall(new Vec3());p.Objects.Add(w);new WallOpeningService().Add(p,w,0,1,2,0,true);Assert.Single(p.WallOpenings);}
[Fact]public void BuilderCreatesManifest(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString());var p=new ShellProject{Name="test_shell"};var r=new FiveMResourceBuilder().Prepare(p,root);Assert.True(File.Exists(Path.Combine(r,"fxmanifest.lua")));Directory.Delete(root,true);}
[Fact]public void RepresentativeShellSupportsGroundAndBasement(){var p=new ShellProject{Name="tc_pipeline_test"};var smart=new SmartBuildingService();foreach(var o in smart.CreateClosedRoom(new Vec3(),8,6,3,.15f,0))p.Objects.Add(o);foreach(var o in smart.AddAdjacentLevel(p,0,-1,3))p.Objects.Add(o);Assert.Contains(p.Objects,x=>x.FloorLevel==0);Assert.Contains(p.Objects,x=>x.FloorLevel==-1);Assert.Contains(p.Objects,x=>x.Type==SceneObjectType.Floor);Assert.Contains(p.Objects,x=>x.Type==SceneObjectType.Ceiling);}
[Fact]public void RepresentativeShellAcceptsDoorAndWindowCuts(){var p=new ShellProject();var smart=new SmartBuildingService();foreach(var o in smart.CreateClosedRoom(new Vec3(),8,6,3,.15f,0))p.Objects.Add(o);var wall=p.Objects.First(x=>x.Type==SceneObjectType.Wall&&x.Scale.X>=8);var svc=new WallOpeningService();svc.Add(p,wall,1,1,2.1f,0,true);svc.Add(p,wall,4,1.2f,1.1f,1,false);Assert.Equal(2,p.WallOpenings.Count);Assert.Contains(p.WallOpenings,x=>x.Door);Assert.Contains(p.WallOpenings,x=>!x.Door);}
[Fact]public void StairMeshProducesGeometry(){var stair=new SceneObject{Name="Test Stairs",Type=SceneObjectType.Stairs,Scale=new Vec3(1.2f,3f,3f)};var mesh=new StairMeshBuilder().Build(stair);Assert.NotEmpty(mesh.Positions);Assert.NotEmpty(mesh.TriangleIndices);}
[Fact]public void GtaValidatorRequiresCollisionAndTextureOutputs(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString());Directory.CreateDirectory(root);var ydr=Path.Combine(root,"shell.ydr");File.WriteAllBytes(ydr,[1]);var issues=new GtaAssetValidator().PipelineIssues([ydr],true,true);Assert.Contains(issues,x=>x.Contains("collision",StringComparison.OrdinalIgnoreCase));Assert.Contains(issues,x=>x.Contains("texture",StringComparison.OrdinalIgnoreCase));Directory.Delete(root,true);}
[Fact]public void FiveMPackagerCopiesVerifiedNativeAssets(){var root=Path.Combine(Path.GetTempPath(),Guid.NewGuid().ToString());var src=Path.Combine(root,"native");Directory.CreateDirectory(src);var ydr=Path.Combine(src,"shell.ydr");var ybn=Path.Combine(src,"shell.ybn");File.WriteAllBytes(ydr,[1]);File.WriteAllBytes(ybn,[1]);var p=new ShellProject{Name="TC Test Shell"};p.Objects.Add(new SceneObject{Name="Wall",Type=SceneObjectType.Wall,Collision=true});var r=new FiveMResourcePackager().Build(p,Path.Combine(root,"out"),[ydr,ybn]);Assert.True(r.Success);Assert.True(File.Exists(Path.Combine(r.ResourcePath,"stream","shell.ydr")));Assert.True(File.Exists(Path.Combine(r.ResourcePath,"stream","shell.ybn")));Assert.True(File.Exists(Path.Combine(r.ResourcePath,"fxmanifest.lua")));Directory.Delete(root,true);}
}
